# 物理资源校验
- name: 校验 master 节点CPU核数
  assert:
    that: ansible_processor_vcpus >= 2
    msg: "Master节点：{{ inventory_hostname }} CPU核数期望不小于2C，实际获取：{{ ansible_memtotal_mb }}C，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['kube-master'] + groups['new-master'])

- name: 校验 worker 节点CPU核数
  assert:
    that: ansible_processor_vcpus >= 2
    msg: "Worker节点：{{ inventory_hostname }} CPU核数期望不小于2C,实际获取：{{ ansible_memtotal_mb }}C，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])