- name: 校验 master 节点内存
  assert:
    that: ansible_memtotal_mb >= 2*1024*0.85
    msg: "Master节点：{{ inventory_hostname }} 内存期望不小于2G，实际获取：{{ ansible_memtotal_mb }}MB，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['kube-master'] + groups['new-master'])

- name: 校验 worker 节点内存
  assert:
    that: ansible_memtotal_mb >= 4*1024*0.85
    msg: "Worker节点：{{ inventory_hostname }} 内存期望不小于4G，实际获取：{{ ansible_memtotal_mb }}MB，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
