# # 删除默认安装
# - name: 删除ubuntu默认安装
#   apt: 
#     name: 
#       - ufw
#       - lxd
#       - lxd-client
#       - lxcfs
#       - lxc-common
#     state: absent

- name: iptables 工具切换到 “旧版” 模式
  shell: "{{ item }} || true"
  with_items:
  - update-alternatives --set iptables /usr/sbin/iptables-legacy
  - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  - update-alternatives --set arptables /usr/sbin/arptables-legacy
  - update-alternatives --set ebtables /usr/sbin/ebtables-legacy
  when: >-
    (ansible_distribution == "Debian" and ansible_distribution_version is version('10', '>=')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('19', '>='))

- name: 判断 ufw 是否安装
  shell: >
    systemctl status ufw | grep active || echo "not be found"
  register: ufw_already_installed

- name: 禁用防火墙
  service:
    name: ufw
    state: stopped
    enabled: no
  when: '"active" in ufw_already_installed.stdout'

- name: 校验安装模式
  assert:
    that: base_apt_repo is defined or base_apt_repo != None
    msg: "当前安装模式为 {{ install_mode }}，请设置变量 base_apt_repo 。"
  when: install_mode != 'online'

- name: 添加基础 Apt 仓库
  apt_repository:
    repo: "{{ base_apt_repo }}"
    state: present
  when: base_apt_repo is defined and base_apt_repo != None
  
# Ubuntu 安装基础软件包
- name: 安装 ubuntu 基础软件
  apt: 
    name:
    - git
    - iotop
    - htop
    - net-tools
    - sysstat
    - libseccomp-dev
    - curl                        # 基础工具
    - apt-transport-https         # 添加https协议的apt源会用到
    - lvm2                        # docker会用到
    - ca-certificates             # docker会用到
    - software-properties-common  # docker会用到
    - nfs-common                  # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
    - conntrack                   # network connection cleanup 用到
    - jq                          # 轻量JSON处理程序，安装docker查询镜像需要
    - socat                       # 用于port forwarding
    - bash-completion             # bash命令补全工具，需要重新登录服务器生效
    - ipset                       # ipvs 模式需要
    - ipvsadm                     # ipvs 模式需要
    - netcat-openbsd              # 使用lb时进行端口判断时会用到
    state: present
    allow_unauthenticated: true

- name: 重新启动 cron 避免因修改时区而导致的作业错乱问题
  service:
    name: cron
    state: restarted
    enabled: yes