name: sync images
on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    paths:
      - 'example/variables.yaml'
jobs:
  sync-dockerhub:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: sync dockerhub images
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://registry-1.docker.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - library/nginx:1.18-alpine
            - library/haproxy:2.1-alpine
            - library/traefik:2.3.1
            - openresty/openresty:1.17.8.2-alpine
            - envoyproxy/envoy:v1.16.0
            - osixia/keepalived:2.0.20
            - calico/typha
            - calico/cni
            - calico/node
            - calico/kube-controllers
            - calico/pod2daemon-flexvol
            - calico/ctl
            - jettech/kube-webhook-certgen
            - kubernetesui/dashboard
            - kubernetesui/metrics-scraper
          replace:
            - old: openresty/
              new: kubeadm-ha/openresty_
            - old: envoyproxy/
              new: kubeadm-ha/envoyproxy_
            - old: osixia/
              new: kubeadm-ha/osixia_
            - old: calico/
              new: kubeadm-ha/calico_
            - old: jettech/
              new: kubeadm-ha/jettech_
            - old: kubernetesui/
              new: kubeadm-ha/kubernetesui_
            - old: library
              new: kubeadm-ha
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          sync-images --config config.yaml

  sync-quay:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: sync quay images
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://quay.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - coreos/flannel
            - jetstack/cert-manager-cainjector
            - jetstack/cert-manager-webhook
            - jetstack/cert-manager-controller
          replace:
            - old: coreos/
              new: kubeadm-ha/coreos_
            - old: jetstack/
              new: kubeadm-ha/jetstack_
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          sync-images --config config.yaml

  sync-gcr:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.1
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: sync gcr images
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://k8s.gcr.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - kube-apiserver
            - kube-controller-manager
            - kube-scheduler
            - kube-proxy
            - pause
            - etcd
            - coredns
            - ingress-nginx/controller
            - metrics-server/metrics-server
          replace:
            - old: ingress-nginx/
              new: kubeadm-ha/ingress-nginx_
            - old: metrics-server/
              new: kubeadm-ha/metrics-server_
            - new: kubeadm-ha
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          sync-images --config config.yaml